site_name: Aaron Alaniz
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode